spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=controller_web;encrypt=true;trustServerCertificate=true;
    username: sa
    password: 123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver